/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ImportantLink = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'category' : IDL.Text,
});
export const PostInput = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'applyLink' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'publishedAt' : IDL.Int,
  'summary' : IDL.Text,
  'featuredImageUrl' : IDL.Text,
  'category' : IDL.Text,
});
export const Post = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'applyLink' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'publishedAt' : IDL.Int,
  'summary' : IDL.Text,
  'featuredImageUrl' : IDL.Text,
  'category' : IDL.Text,
});
export const BreakingNewsItem = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBreakingNews' : IDL.Func([IDL.Text], [], []),
  'createImportantLink' : IDL.Func([ImportantLink], [], []),
  'createPost' : IDL.Func([PostInput], [], []),
  'deleteBreakingNews' : IDL.Func([IDL.Text], [], []),
  'deleteImportantLink' : IDL.Func([IDL.Text], [], []),
  'deletePost' : IDL.Func([IDL.Text], [], []),
  'getAllImportantLinks' : IDL.Func([], [IDL.Vec(ImportantLink)], ['query']),
  'getAllPublishedPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getLatestBreakingNews' : IDL.Func(
      [],
      [IDL.Vec(BreakingNewsItem)],
      ['query'],
    ),
  'getPostsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
  'searchPostsByTitle' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
  'updateImportantLink' : IDL.Func([ImportantLink], [], []),
  'updatePost' : IDL.Func([PostInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ImportantLink = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'category' : IDL.Text,
  });
  const PostInput = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'applyLink' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'publishedAt' : IDL.Int,
    'summary' : IDL.Text,
    'featuredImageUrl' : IDL.Text,
    'category' : IDL.Text,
  });
  const Post = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'applyLink' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'publishedAt' : IDL.Int,
    'summary' : IDL.Text,
    'featuredImageUrl' : IDL.Text,
    'category' : IDL.Text,
  });
  const BreakingNewsItem = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
  });
  
  return IDL.Service({
    'addBreakingNews' : IDL.Func([IDL.Text], [], []),
    'createImportantLink' : IDL.Func([ImportantLink], [], []),
    'createPost' : IDL.Func([PostInput], [], []),
    'deleteBreakingNews' : IDL.Func([IDL.Text], [], []),
    'deleteImportantLink' : IDL.Func([IDL.Text], [], []),
    'deletePost' : IDL.Func([IDL.Text], [], []),
    'getAllImportantLinks' : IDL.Func([], [IDL.Vec(ImportantLink)], ['query']),
    'getAllPublishedPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getLatestBreakingNews' : IDL.Func(
        [],
        [IDL.Vec(BreakingNewsItem)],
        ['query'],
      ),
    'getPostsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
    'searchPostsByTitle' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
    'updateImportantLink' : IDL.Func([ImportantLink], [], []),
    'updatePost' : IDL.Func([PostInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };