/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BreakingNewsItem {
    id: string;
    createdAt: bigint;
    text: string;
}
export interface PostInput {
    id: string;
    title: string;
    content: string;
    isPublished: boolean;
    applyLink: string;
    tags: Array<string>;
    publishedAt: bigint;
    summary: string;
    featuredImageUrl: string;
    category: string;
}
export interface Post {
    id: string;
    title: string;
    content: string;
    isPublished: boolean;
    applyLink: string;
    tags: Array<string>;
    publishedAt: bigint;
    summary: string;
    featuredImageUrl: string;
    category: string;
}
export interface ImportantLink {
    id: string;
    url: string;
    title: string;
    category: string;
}
export interface backendInterface {
    addBreakingNews(text: string): Promise<void>;
    createImportantLink(link: ImportantLink): Promise<void>;
    createPost(post: PostInput): Promise<void>;
    deleteBreakingNews(newsId: string): Promise<void>;
    deleteImportantLink(linkId: string): Promise<void>;
    deletePost(postId: string): Promise<void>;
    /**
     * / Important Links Management
     */
    getAllImportantLinks(): Promise<Array<ImportantLink>>;
    /**
     * / Posts Management
     */
    getAllPublishedPosts(): Promise<Array<Post>>;
    /**
     * / Breaking News Management
     */
    getLatestBreakingNews(): Promise<Array<BreakingNewsItem>>;
    getPostsByCategory(category: string): Promise<Array<Post>>;
    searchPostsByTitle(searchTerm: string): Promise<Array<Post>>;
    updateImportantLink(link: ImportantLink): Promise<void>;
    updatePost(post: PostInput): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addBreakingNews(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBreakingNews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBreakingNews(arg0);
            return result;
        }
    }
    async createImportantLink(arg0: ImportantLink): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createImportantLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createImportantLink(arg0);
            return result;
        }
    }
    async createPost(arg0: PostInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0);
            return result;
        }
    }
    async deleteBreakingNews(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBreakingNews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBreakingNews(arg0);
            return result;
        }
    }
    async deleteImportantLink(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteImportantLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteImportantLink(arg0);
            return result;
        }
    }
    async deletePost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async getAllImportantLinks(): Promise<Array<ImportantLink>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllImportantLinks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllImportantLinks();
            return result;
        }
    }
    async getAllPublishedPosts(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublishedPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublishedPosts();
            return result;
        }
    }
    async getLatestBreakingNews(): Promise<Array<BreakingNewsItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestBreakingNews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestBreakingNews();
            return result;
        }
    }
    async getPostsByCategory(arg0: string): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostsByCategory(arg0);
            return result;
        }
    }
    async searchPostsByTitle(arg0: string): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchPostsByTitle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchPostsByTitle(arg0);
            return result;
        }
    }
    async updateImportantLink(arg0: ImportantLink): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateImportantLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateImportantLink(arg0);
            return result;
        }
    }
    async updatePost(arg0: PostInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePost(arg0);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
